name: Publish Release

on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .
    - name: Build
      run: |
        VERSION=$(<VERSION)
        # Copy keymaps for all platforms (for some reason, Default.sublime-keymap doesn't always works)
        # cp ./Default.sublime-keymap ./Default\ \(OSX\).sublime-keymap
        # cp ./Default.sublime-keymap ./Default\ \(Windows\).sublime-keymap
        # cp ./Default.sublime-keymap ./Default\ \(Linux\).sublime-keymap
        # rm ./Default.sublime-keymap
        zip -x "*.pyc" -x "__pycache__" -r Emmet.sublime-package emmet messages messages.json lib *.py *.sublime-* .python-version VERSION LICENSE
        mkdir -p public/$VERSION
        python tools/registry.py > public/registry.json
        cp ./Emmet.sublime-package ./public/$VERSION/Emmet.sublime-package
    # - name: GH Release
    #   uses: softprops/action-gh-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     files: |
    #       Emmet.zip
    #       registry.json
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: download # The branch the action should deploy to.
        folder: public # The folder the action should deploy.


