name: Publish Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .
    - name: Build
      run: |
        rm ./__init__.py
        # Copy keymaps for all platforms (for some reason, Default.sublime-keymap doesn't always works)
        cp ./Default.sublime-keymap ./Default\ \(OSX\).sublime-keymap
        cp ./Default.sublime-keymap ./Default\ \(Windows\).sublime-keymap
        cp ./Default.sublime-keymap ./Default\ \(Linux\).sublime-keymap
        rm ./Default.sublime-keymap
        zip -x "*.pyc" -x "__pycache__" -r Emmet.zip emmet *.py *.sublime-*
        python tools/registry.py > registry.json
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.0
      with:
        files: |
          Emmet.zip
          registry.json
  
